### ISSUE TITLE
A question about how to test retrieval

### ISSUE THREAD

**Issue by gimpong** [leeesangwon/PyTorch-Image-Retrieval#15]
Hi, thank you for building such a useful and concise framework for image retrival task!

I just read the file `inference.py` and got confused about the testing process.

https://github.com/leeesangwon/PyTorch-Image-Retrieval/blob/811625199579fe627d2d1a4f9e31ea022d4a40b2/inference.py#L20-L23

My question is, why is the database for retrieval getting divided into batches? Shouldn't we keep it as a whole for every query, since we want to rank **all the reference images in *whole* database** according to the pair-wise similarity?

**Comment by leeesangwon** [comment]
In the `batch_process` function, all feature vectors are concatenated.

https://github.com/leeesangwon/PyTorch-Image-Retrieval/blob/811625199579fe627d2d1a4f9e31ea022d4a40b2/inference.py#L28-L29

https://github.com/leeesangwon/PyTorch-Image-Retrieval/blob/811625199579fe627d2d1a4f9e31ea022d4a40b2/inference.py#L111-L122
